### ISSUE TITLE
How do I deploy this on my server?

### ISSUE THREAD

**Issue by Kondra007** [JochemKuijpers/ZombieBot#1]
1) If I download your zombie.py and place it somewhere on my server..what else do I have to do? How to send users' messages to this zombie.py file?

2) How to get user's chat_id ?

**Comment by JochemKuijpers** [comment]
1) Copy zombie.py some folder on your computer or server. Create a second file: `config.py` and put your Bot API key here: 

    token = 'your_key_here'

Now run `python3 zombie.py`

I guess I could add a shebang line so you can just execute the script without explicitly calling `python3`. I might do that later.

2) The chat_id of a user (as opposed to a group) is equal to the id you find in `update['message']['from']['id']` If you want more insight in the structure of these updates, I suggest you look at the Telegram Bot API or open the getUpdates URL in your browser and copy/paste it in http://jsbeautifier.org/ or a similar service.

Please let me know if you are satisfied with these answers so I can close this issue.

**Comment by Kondra007** [comment]
Just one more question, okay?
When I copy zombie.py to my server or computer and run it, do I have to add something to bot settings via BotFather? Any webhooks or something like that? 
I mean, how my Telegram bot is supposed to send commands to server and how can server recieve them?

**Comment by JochemKuijpers** [comment]
Yes, you need to create your own bot by using `/newbot` and following these instructions. BotFather should give you a token, which you place in `config.py`. If it doesn't give you your token, you can request a new one via `/token`.

With this token, `zombie.py` is able to receive updates of your bot and send messages.

**Comment by Kondra007** [comment]
I've already registered bot and have token.

If I understand you right, script just makes getUpdates GET-request for new messages ti bot?

**Comment by JochemKuijpers** [comment]
It's actually a POST-request, but they are essentially the same in Telegram's Bot API. If you want to ask specific questions about the bot, please contact me on telegram. I'll close this issue now since it's not an issue related to the bot :)
